# This is a basic workflow that is manually triggered

name: ci-build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:    
      - main 
  pull_request:
    branches:    
      - main 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: checkout current project  
      uses: actions/checkout@v2.4.0
    - 
      name: gambas install
      run: |
        sudo add-apt-repository -y ppa:gambas-team/gambas3
        sudo apt update
        sudo apt install -y gambas3 gambas3-gb-form-print     
    - 
      name: gambas build
      run: /usr/bin/gbc3

